# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n\x04Post\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x13\n\tvideo_url\x18\x03 \x01(\tH\x00\x12\x13\n\timage_url\x18\x04 \x01(\tH\x00\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x05\x12\x19\n\x05state\x18\x07 \x01(\x0e\x32\n.PostState\x12\x34\n\x10publication_date\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x07\n\x05media*9\n\tPostState\x12\x0f\n\x0bPOST_NORMAL\x10\x00\x12\n\n\x06LOCKED\x10\x01\x12\x0f\n\x0bPOST_HIDDEN\x10\x02\x32\x0e\n\x0cPostServicerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSTSTATE']._serialized_start=248
  _globals['_POSTSTATE']._serialized_end=305
  _globals['_POST']._serialized_start=48
  _globals['_POST']._serialized_end=246
  _globals['_POSTSERVICER']._serialized_start=307
  _globals['_POSTSERVICER']._serialized_end=321
# @@protoc_insertion_point(module_scope)
