# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_monitor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14update_monitor.proto\"\x1b\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2N\n\x15UpdateMonitorServicer\x12\x35\n\x0eMonitorUpdates\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'update_monitor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATEREQUEST']._serialized_start=24
  _globals['_UPDATEREQUEST']._serialized_end=51
  _globals['_UPDATERESPONSE']._serialized_start=53
  _globals['_UPDATERESPONSE']._serialized_end=85
  _globals['_UPDATEMONITORSERVICER']._serialized_start=87
  _globals['_UPDATEMONITORSERVICER']._serialized_end=165
# @@protoc_insertion_point(module_scope)
